# Construbot documentation build configuration file
#
# This file is execfile()d with the current directory set to its containing dir.

import os
import sys
import django

# -- Path setup --------------------------------------------------------------

# Add the project root directory to sys.path for autodoc
sys.path.insert(0, os.path.abspath('..'))

# -- Django setup for autodoc ------------------------------------------------

# Configure Django settings for autodoc to import models
os.environ['DJANGO_SETTINGS_MODULE'] = 'construbot.config.settings.local'
os.environ['DJANGO_READ_DOT_ENV_FILE'] = 'False'
os.environ.setdefault('DATABASE_URL', 'sqlite:///:memory:')
os.environ.setdefault('CELERY_BROKER_URL', 'redis://localhost:6379/0')
os.environ.setdefault('DJANGO_SECRET_KEY', 'docs-secret-key-not-for-production')
os.environ.setdefault('DJANGO_ADMIN_URL', r'^admin/')
os.environ.setdefault('DJANGO_DEBUG', 'False')

# Initialize Django
django.setup()

# -- Project information -----------------------------------------------------

project = 'Construbot'
copyright = '2018-2025, Javier Llamas Ramirez'
author = 'Javier Llamas Ramirez'

# The version info for the project you're documenting
# Read from construbot/__init__.py
try:
    import construbot
    version = construbot.__version__  # Short version: 1.1.04
    release = construbot.__version__  # Full version: 1.1.04
except ImportError:
    version = '1.1.04'
    release = '1.1.04'

# -- General configuration ---------------------------------------------------

# Sphinx extensions
extensions = [
    # Core Sphinx extensions
    'sphinx.ext.autodoc',           # Auto-generate API docs from docstrings
    'sphinx.ext.napoleon',          # Support Google/NumPy docstring styles
    'sphinx.ext.viewcode',          # Add links to source code
    'sphinx.ext.intersphinx',       # Link to other projects' docs
    'sphinx.ext.todo',              # Support TODO notes
    'sphinx.ext.coverage',          # Check documentation coverage
    'sphinx.ext.autosummary',       # Generate summary tables

    # External extensions
    'sphinxcontrib.httpdomain',     # Document HTTP APIs
    'sphinx_tabs.tabs',             # Tabbed content (Docker/Local)
    'sphinx_copybutton',            # Copy button for code blocks
]

# Add any paths that contain templates here, relative to this directory
templates_path = ['_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The master toctree document
master_doc = 'index'

# The suffix of source filenames
source_suffix = '.rst'

# The language for content autogenerated by Sphinx
language = 'en'  # Primary language is English

# Internationalization configuration
locale_dirs = ['locale/']
gettext_compact = False  # Create separate PO files for each document

# The name of the Pygments (syntax highlighting) style to use
pygments_style = 'sphinx'

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages
html_theme = 'furo'

# Theme options are theme-specific and customize the look and feel
# Furo theme options: https://pradyunsg.me/furo/customisation/
html_theme_options = {
    "light_css_variables": {
        "color-brand-primary": "#2980B9",
        "color-brand-content": "#2980B9",
    },
    "dark_css_variables": {
        "color-brand-primary": "#3498DB",
        "color-brand-content": "#3498DB",
    },
    "sidebar_hide_name": False,
    "navigation_with_keys": True,
    "top_of_page_button": "edit",

    # Footer and source links
    "source_repository": "https://github.com/javier-llamas/construbot",
    "source_branch": "master",
    "source_directory": "docs/",

    # Footer text
    "footer_icons": [
        {
            "name": "GitHub",
            "url": "https://github.com/javier-llamas/construbot",
            "html": """
                <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0 0 16 8c0-4.42-3.58-8-8-8z"></path>
                </svg>
            """,
            "class": "",
        },
    ],
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css"
html_static_path = ['_static']

# Custom CSS files
html_css_files = [
    'css/custom.css',
]

# The name of an image file (relative to this directory) to place at the top
# of the sidebar
# html_logo = '_static/images/construbot-logo.png'  # Uncomment when logo exists

# The name of an image file (within the static path) to use as favicon
# html_favicon = '_static/images/favicon.ico'  # Uncomment when favicon exists

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom
html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities
html_use_smartypants = True

# Output file base name for HTML help builder
htmlhelp_basename = 'construbotdoc'

# GitHub integration context
html_context = {
    'display_github': True,
    'github_user': 'javier-llamas',
    'github_repo': 'construbot',
    'github_version': 'master',
    'conf_py_path': '/docs/',
}

# -- Options for autodoc -----------------------------------------------------

# Autodoc configuration to handle limited docstrings
autodoc_default_options = {
    'members': True,
    'member-order': 'bysource',
    'special-members': '__init__',
    'undoc-members': True,  # Include even if no docstring
    'exclude-members': '__weakref__,DoesNotExist,MultipleObjectsReturned,objects',
    'show-inheritance': True,
}

# Generate stub documentation for undocumented items
autodoc_mock_imports = []
autoclass_content = 'both'  # Include __init__ docstring and class docstring
autodoc_typehints = 'description'  # Show type hints in description

# -- Options for napoleon ----------------------------------------------------

# Napoleon settings for parsing docstrings
napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = True
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = False
napoleon_use_admonition_for_notes = False
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True
napoleon_preprocess_types = False
napoleon_type_aliases = None
napoleon_attr_annotations = True

# -- Options for intersphinx -------------------------------------------------

# Intersphinx configuration for linking to other docs
intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),
    'django': ('https://docs.djangoproject.com/en/3.2/', 'https://docs.djangoproject.com/en/3.2/_objects/'),
    'drf': ('https://www.django-rest-framework.org', None),
}

# -- Options for todo extension ----------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing
todo_include_todos = True

# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    'papersize': 'letterpaper',
    'pointsize': '10pt',
    'preamble': '',
    'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files
latex_documents = [
    (master_doc, 'construbot.tex', 'Construbot Documentation',
     'Javier Llamas Ramirez', 'manual'),
]

# -- Options for manual page output ------------------------------------------

# One entry per manual page
man_pages = [
    (master_doc, 'construbot', 'Construbot Documentation',
     [author], 1)
]

# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files
texinfo_documents = [
    (master_doc, 'construbot', 'Construbot Documentation',
     author, 'Construbot', 'Una Solucion operativa para constructoras',
     'Miscellaneous'),
]

# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info
epub_title = project
epub_author = author
epub_publisher = author
epub_copyright = copyright

# The unique identifier of the text
# epub_identifier = ''

# A unique identification for the text
# epub_uid = ''

# A list of files that should not be packed into the epub file
epub_exclude_files = ['search.html']

# -- Extension configuration -------------------------------------------------

# sphinx-tabs configuration
sphinx_tabs_disable_tab_closing = True

# sphinx-copybutton configuration
copybutton_prompt_text = r">>> |\.\.\. |\$ |In \[\d*\]: | {2,5}\.\.\.: | {5,8}: "
copybutton_prompt_is_regexp = True
copybutton_remove_prompts = True
